[package]
name = "hello_world"
version = "0.0.0"

[addresses]
Std = "0x1" # Specify and assign 0x1 to the named address "Std"

[dependencies]
MoveNursery = { git = "https://github.com/diem/move.git", subdir = "language/move-stdlib/nursery", rev = "d45f20a" }
#                ^                    ^                     ^                                       ^
#            Git dependency       Git clone URL       Subdir under git repo (optional)           Git revision to use
